# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import person_pb2 as person__pb2


class SalutationStub(object):
    """The salutation service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Salutation = channel.unary_unary(
            "/Salutation/Salutation",
            request_serializer=person__pb2.SalutationRequest.SerializeToString,
            response_deserializer=person__pb2.SalutationReply.FromString,
        )


class SalutationServicer(object):
    """The salutation service definition.
    """

    def Salutation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SalutationServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Salutation": grpc.unary_unary_rpc_method_handler(
            servicer.Salutation,
            request_deserializer=person__pb2.SalutationRequest.FromString,
            response_serializer=person__pb2.SalutationReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Salutation", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Salutation(object):
    """The salutation service definition.
    """

    @staticmethod
    def Salutation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Salutation/Salutation",
            person__pb2.SalutationRequest.SerializeToString,
            person__pb2.SalutationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
