# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="person.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0cperson.proto"!\n\x11SalutationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t""\n\x0fSalutationReply\x12\x0f\n\x07message\x18\x02 \x01(\t2B\n\nSalutation\x12\x34\n\nSalutation\x12\x12.SalutationRequest\x1a\x10.SalutationReply"\x00\x62\x06proto3',
)


_SALUTATIONREQUEST = _descriptor.Descriptor(
    name="SalutationRequest",
    full_name="SalutationRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="SalutationRequest.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=16,
    serialized_end=49,
)


_SALUTATIONREPLY = _descriptor.Descriptor(
    name="SalutationReply",
    full_name="SalutationReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="SalutationReply.message",
            index=0,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=51,
    serialized_end=85,
)

DESCRIPTOR.message_types_by_name["SalutationRequest"] = _SALUTATIONREQUEST
DESCRIPTOR.message_types_by_name["SalutationReply"] = _SALUTATIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SalutationRequest = _reflection.GeneratedProtocolMessageType(
    "SalutationRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _SALUTATIONREQUEST,
        "__module__": "person_pb2"
        # @@protoc_insertion_point(class_scope:SalutationRequest)
    },
)
_sym_db.RegisterMessage(SalutationRequest)

SalutationReply = _reflection.GeneratedProtocolMessageType(
    "SalutationReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _SALUTATIONREPLY,
        "__module__": "person_pb2"
        # @@protoc_insertion_point(class_scope:SalutationReply)
    },
)
_sym_db.RegisterMessage(SalutationReply)


_SALUTATION = _descriptor.ServiceDescriptor(
    name="Salutation",
    full_name="Salutation",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=87,
    serialized_end=153,
    methods=[
        _descriptor.MethodDescriptor(
            name="Salutation",
            full_name="Salutation.Salutation",
            index=0,
            containing_service=None,
            input_type=_SALUTATIONREQUEST,
            output_type=_SALUTATIONREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_SALUTATION)

DESCRIPTOR.services_by_name["Salutation"] = _SALUTATION

# @@protoc_insertion_point(module_scope)
