# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=1024']
    - id: check-json
      types: [file]  # override `types: [json]`
      files: \.(json|ipynb)$
    - id: check-toml
    - id: check-yaml
      types: [file]
      files: \.(yml|yaml|cff)$
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 6e10264313f53d6247a8b1b984f5b5ccf50ba539 # 2.21.0
    hooks:
    - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: 4b2e70d08cb2ccd26d1fba73588de41c7a5d50b7 # v0.25
    hooks:
    - id: validate-pyproject
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: c883505f64b59c3c5c9375191e4ad9f98e727ccd # v1.0.2
    hooks:
    - id: sphinx-lint
      types: [rst]
  - repo: https://github.com/pycqa/isort
    rev: a333737ed43df02b18e6c95477ea1b285b3de15a # 8.0.1
    hooks:
    - id: isort
      additional_dependencies: ["toml"]
      entry: isort --profile=black
      name: isort (python)
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: fa505ab9c3e0fedafe1709fd7ac2b5f8996c670d # 26.3.1
    hooks:
    - id: black
  - repo: https://github.com/adamchainz/blacken-docs
    rev: fda77690955e9b63c6687d8806bafd56a526e45f # 1.20.0
    hooks:
    - id: blacken-docs
      args: [--line-length=79]
      additional_dependencies:
      - black
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # v2.4.2
    hooks:
    - id: codespell
  - repo: local
    hooks:
    - id: linkcheck
      entry: sphinx-build -b linkcheck docs _build/html
      name: linkcheck
      language: system
      files: $(git diff --staged --name-only "*")
