# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import accounts_pb2 as accounts__pb2
import grpc


class AccountsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccount = channel.unary_unary(
            "/Accounts/CreateAccount",
            request_serializer=accounts__pb2.CreateAccountRequest.SerializeToString,
            response_deserializer=accounts__pb2.CreateAccountResult.FromString,
        )
        self.GetAccounts = channel.unary_stream(
            "/Accounts/GetAccounts",
            request_serializer=accounts__pb2.GetAccountsRequest.SerializeToString,
            response_deserializer=accounts__pb2.GetAccountsResult.FromString,
        )


class AccountsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AccountsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateAccount": grpc.unary_unary_rpc_method_handler(
            servicer.CreateAccount,
            request_deserializer=accounts__pb2.CreateAccountRequest.FromString,
            response_serializer=accounts__pb2.CreateAccountResult.SerializeToString,
        ),
        "GetAccounts": grpc.unary_stream_rpc_method_handler(
            servicer.GetAccounts,
            request_deserializer=accounts__pb2.GetAccountsRequest.FromString,
            response_serializer=accounts__pb2.GetAccountsResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Accounts", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Accounts(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAccount(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Accounts/CreateAccount",
            accounts__pb2.CreateAccountRequest.SerializeToString,
            accounts__pb2.CreateAccountResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetAccounts(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Accounts/GetAccounts",
            accounts__pb2.GetAccountsRequest.SerializeToString,
            accounts__pb2.GetAccountsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
