name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  docs:
    name: Build docs and check links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pandoc/actions/setup@v1
    - uses: ts-graphviz/setup-graphviz@v2
    - uses: actions/setup-python@v5
      with:
        cache: pip
        # Keep in sync with .readthedocs.yaml
        python-version-file: .python-version
    - run: python -m pip install -e ".[docs]"
    - run: python -m sphinx -nb html docs/ docs/_build/html
    - run: python -m sphinx -b linkcheck docs/ docs/_build/html
