name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  docs:
    name: Build docs and check links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: pandoc/actions/setup@v1
    - uses: ts-graphviz/setup-graphviz@v2
    - uses: actions/setup-python@v6
      with:
        # Keep in sync with .readthedocs.yaml
        python-version-file: .python-version
    - name: Setup cached uv
      uses: hynek/setup-cached-uv@v2
    - name: Create venv and install docs dependencies
      run: |
        uv venv
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
        uv pip install --group=docs
    - name: Build HTML and check links
      run: |
        uv run make html
        uv run make linkcheck
      working-directory: docs/
